name: Tests
on: push
env:
  MIX_ENV: test
  OTP_VERSION: 23.0.3
  ELIXIR_VERSION: 1.10.4

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      QT_QPA_PLATFORM: offscreen

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-elixir@main
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Cache Deps
        uses: actions/cache@main
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-mix-

      - name: Cache Build
        uses: actions/cache@main
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-build-${{ env.MIX_ENV }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-build-${{ env.MIX_ENV }}-

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends wkhtmltopdf

      - run: mix do deps.get, compile
      - run: mix coveralls.json

      - name: Upload Coverage Report to Codecov
        run: bash <(curl -s https://codecov.io/bash)

  formatter:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-elixir@main
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Cache Deps
        uses: actions/cache@main
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-mix-

      - name: Cache Build
        uses: actions/cache@main
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-build-${{ env.MIX_ENV }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-build-${{ env.MIX_ENV }}-

      - run: mix do deps.get, compile
      - run: mix format --check-formatted
